# Generated by Django 6.0 on 2026-01-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0006_rename_highest_qualification_application_education_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_check', models.BooleanField(default=False)),
                ('programme_level_check', models.BooleanField(default=False)),
                ('exam_foundation_spm', models.BooleanField(default=False)),
                ('exam_degree_stpm_uec', models.BooleanField(default=False)),
                ('exam_degree_matriculation', models.BooleanField(default=False)),
                ('grade_spm', models.BooleanField(default=False)),
                ('grade_stpm', models.BooleanField(default=False)),
                ('grade_uec', models.BooleanField(default=False)),
                ('grade_foundation', models.BooleanField(default=False)),
                ('documents_verified', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_check', to='student.application')),
            ],
        ),
    ]
