# Generated by Django 4.2.27 on 2026-01-22 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_application_unique_together_and_more'),
        ('reviewer', '0002_rename_minimum_grades_check_eligibilitycheck_exam_degree_matriculation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='eligibilitycheck',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_check', to='student.application'),
        ),
        migrations.AlterField(
            model_name='eligibilitycheck',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
