# Generated by Django 6.0.1 on 2026-01-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0006_eligibilitycheck_competition_national_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycheck',
            name='financial_priority',
            field=models.CharField(blank=True, choices=[('1', '(1) Low Need (T20)'), ('2', '(2) Moderate Need (M40)'), ('3', '(3) High Need (B40)'), ('4', '(4) Critical Need (B40)')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='hardship_large_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='hardship_medical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='hardship_retiree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='hardship_single_income',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='integrity_income_check',
            field=models.BooleanField(default=False),
        ),
    ]
