# Generated by Django 6.0 on 2026-01-26 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(choices=[('q1', 'What is the name of your first pet?'), ('q2', "What is your mother's maiden name?"), ('q3', 'What was the name of your elementary school?'), ('q4', 'What is the name of the city where you were born?'), ('q5', 'What is your favorite food?'), ('q6', 'What is the name of your favorite teacher?'), ('q7', "What is your father's middle name?"), ('q8', 'What is the make of your first car?'), ('q9', 'What is your favorite movie?'), ('q10', 'What is your favorite book?')], max_length=50)),
                ('answer_1', models.CharField(max_length=255)),
                ('question_2', models.CharField(choices=[('q1', 'What is the name of your first pet?'), ('q2', "What is your mother's maiden name?"), ('q3', 'What was the name of your elementary school?'), ('q4', 'What is the name of the city where you were born?'), ('q5', 'What is your favorite food?'), ('q6', 'What is the name of your favorite teacher?'), ('q7', "What is your father's middle name?"), ('q8', 'What is the make of your first car?'), ('q9', 'What is your favorite movie?'), ('q10', 'What is your favorite book?')], max_length=50)),
                ('answer_2', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
