# Generated by Django 6.0 on 2026-01-21 07:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committee', '0008_delete_reviewchecklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_gpa', models.FloatField(help_text='Current Grade Point Average')),
                ('course', models.CharField(help_text='Name of the enrolled course', max_length=50)),
                ('year_of_study', models.PositiveSmallIntegerField(help_text='Current year of study')),
                ('student_type', models.CharField(choices=[('International Student', 'International Student'), ('Local', 'Local')], help_text='Student types, either international student or local', max_length=50)),
                ('education_level', models.CharField(choices=[('Foundation', 'Foundation'), ('Undergraduate', 'Undergraduate'), ('Diploma', 'Diploma'), ('Postgraduate', 'Postgraduate')], help_text='Level of education: foundation, diploma, undergraduate or postgraduate', max_length=50)),
                ('extracurricular_activities', models.TextField(blank=True, help_text='List of extracurricular activities', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now, help_text='Date when the bookmark was added')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='committee.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='student.student')),
            ],
            options={
                'unique_together': {('student', 'scholarship')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the application was submitted')),
                ('status', models.CharField(default='Pending', help_text='Current status of the application', max_length=50)),
                ('interview_status', models.CharField(default='Not Scheduled', help_text='Status of the interview related to application', max_length=50)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='committee.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='student.student')),
            ],
            options={
                'unique_together': {('student', 'scholarship')},
            },
        ),
    ]
