# Generated by Django 4.2.27 on 2026-01-26 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('home_address', models.TextField()),
                ('correspondence_address', models.TextField()),
                ('ic_no', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('intake', models.DateField()),
                ('programme', models.CharField(max_length=200)),
                ('student_identification_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(choices=[('International Student', 'International Student'), ('Local', 'Local')], max_length=100)),
                ('race', models.CharField(choices=[('Malay', 'Malay'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Other', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('contact_number', models.CharField(max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('email_address', models.EmailField(max_length=254)),
                ('education_level', models.CharField(choices=[('Foundation', 'Foundation'), ('Undergraduate', 'Undergraduate'), ('Diploma', 'Diploma'), ('Postgraduate', 'Postgraduate')], max_length=200)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='passport_photos/')),
                ('academic_result', models.FileField(blank=True, null=True, upload_to='academic_results/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='supporting_docs/')),
                ('personal_achievement', models.TextField(blank=True, null=True)),
                ('reason_deserve', models.TextField(blank=True, null=True)),
                ('ea_form', models.FileField(blank=True, null=True, upload_to='ea_forms/')),
                ('payslip', models.FileField(blank=True, null=True, upload_to='payslips/')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.scholarship')),
            ],
            options={
                'db_table': 'student_application',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_gpa', models.FloatField(blank=True, help_text='Current Grade Point Average', null=True)),
                ('course', models.CharField(blank=True, help_text='Name of the enrolled course', max_length=50, null=True)),
                ('year_of_study', models.PositiveSmallIntegerField(blank=True, help_text='Current year of study', null=True)),
                ('student_type', models.CharField(blank=True, choices=[('International Student', 'International Student'), ('Local', 'Local')], help_text='Student types, either international student or local', max_length=50, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Undergraduate', 'Undergraduate'), ('Diploma', 'Diploma'), ('Postgraduate', 'Postgraduate')], help_text='Level of education: foundation, diploma, undergraduate or postgraduate', max_length=50, null=True)),
                ('extracurricular_activities', models.TextField(blank=True, help_text='List of extracurricular activities', max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interview_time', models.CharField(default='12:00 PM', max_length=20)),
                ('timezone', models.CharField(max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='student.application')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('ic_no', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='student.application')),
            ],
            options={
                'db_table': 'student_guardian',
            },
        ),
        migrations.CreateModel(
            name='ApprovedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('ic_no', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('programme', models.CharField(max_length=200)),
                ('interview_date', models.DateField()),
                ('interview_time', models.CharField(max_length=20)),
                ('interview_timezone', models.CharField(max_length=50)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.application')),
            ],
            options={
                'db_table': 'approved_applications',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now, help_text='Date when the bookmark was added')),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='committee.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='student.student')),
            ],
            options={
                'unique_together': {('student', 'scholarship')},
            },
        ),
    ]
