# Generated by Django 4.2.27 on 2026-01-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='personal_achievement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='race',
            field=models.CharField(choices=[('Malay', 'Malay'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='reason_deserve',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='scholarship',
            field=models.CharField(max_length=200),
        ),
    ]
