# Generated by Django 6.0 on 2026-02-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='a_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, help_text='e.g. SPM, STPM, UEC, Foundation', max_length=100, null=True),
        ),
    ]
