# Generated by Django 6.0 on 2026-01-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='status',
            new_name='committee_status',
        ),
        migrations.AddField(
            model_name='application',
            name='reviewer_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
