# Generated by Django 6.0 on 2026-01-26 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitted_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when the application was submitted'),
        ),
    ]
