# Generated by Django 4.2.27 on 2026-02-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='acceptance_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', help_text="Student's decision after committee approval", max_length=20),
        ),
    ]
