# Generated by Django 4.2.27 on 2026-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='iscomplete',
            field=models.BooleanField(default=False),
        ),
    ]
