# Generated by Django 6.0.1 on 2026-01-25 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_scholarshipapplication_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='submitted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
