# Generated by Django 4.2.27 on 2026-01-23 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
        ('student', '0002_alter_application_personal_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='scholarship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.scholarship'),
        ),
    ]
