# Generated by Django 4.2.27 on 2026-02-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_application_acceptance_status'),
        ('student', '0002_student_a_count_student_qualification'),
    ]

    operations = [
    ]
