# Generated by Django 4.2.27 on 2026-01-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_application_scholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='monthly_income',
        ),
        migrations.AddField(
            model_name='application',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=12),
            preserve_default=False,
        ),
    ]
