# Generated by Django 4.2.27 on 2026-02-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_merge_20260201_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('SPM', 'SPM'), ('STPM', 'STPM'), ('UEC', 'UEC'), ('Matriculation', 'Matriculation'), ('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('A-Level', 'A-Level'), ('IB', 'International Baccalaureate'), ('Other', 'Other')], help_text='The highest academic qualification you have completed (e.g. STPM, UEC)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Undergraduate', 'Undergraduate'), ('Diploma', 'Diploma'), ('Postgraduate', 'Postgraduate')], help_text='Level of education snapshot at time of application', max_length=50, null=True),
        ),
    ]
