# Generated by Django 4.2.27 on 2026-01-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_application_iscomplete'),
        ('student', '0003_application_assigned_committee_member_and_more'),
    ]

    operations = [
    ]
