# Generated by Django 4.2.27 on 2026-02-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_application_highest_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='education_level',
        ),
    ]
