# Generated by Django 4.2.27 on 2026-01-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_guardian_monthly_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='highest_qualification',
            field=models.CharField(choices=[('Foundation', 'Foundation'), ('Undergraduate', 'Undergraduate'), ('Diploma', 'Diploma'), ('Postgraduate', 'Postgraduate')], max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.CharField(choices=[('International Student', 'International Student'), ('Local', 'Local')], max_length=100),
        ),
    ]
