# Generated by Django 4.2.27 on 2026-02-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_application_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Undergraduate', 'Undergraduate'), ('Diploma', 'Diploma'), ('Postgraduate', 'Postgraduate')], help_text='Level of education snapshot at time of application', max_length=50, null=True),
        ),
    ]
