# Generated by Django 4.2.27 on 2026-01-30 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_application_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Application', 'Application'), ('System', 'System'), ('Reminder', 'Reminder')], default='System', max_length=20)),
                ('message', models.TextField(help_text='Notification message content')),
                ('is_read', models.BooleanField(default=False)),
                ('display_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date the notification should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the notification was created')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
