# Generated by Django 4.2.27 on 2026-01-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_application_highest_qualification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='highest_qualification',
            new_name='education_level',
        ),
    ]
