# Generated by Django 6.0 on 2026-02-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_application_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='reviewer_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected'), ('In-Progress', 'In-Progress')], default='Pending', max_length=20),
        ),
    ]
