# Generated by Django 4.2.27 on 2026-02-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_application_reviewer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='highest_qualification_gpa',
            field=models.FloatField(blank=True, help_text='CGPA for your previous/highest qualification (e.g. Foundation, Diploma)', null=True),
        ),
    ]
