# Generated by Django 6.0 on 2026-02-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_highest_qualification_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='a_count',
            field=models.PositiveIntegerField(blank=True, help_text="Number of A's in your highest qualification (e.g. SPM)", null=True),
        ),
    ]
