# Generated by Django 6.0 on 2026-01-31 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('interview_time', models.CharField(default='12:00 PM', max_length=20)),
                ('timezone', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('open_for', models.CharField(max_length=200)),
                ('education_level', models.CharField(choices=[('Foundation', 'Foundation'), ('Undergraduate', 'Undergraduate'), ('Diploma', 'Diploma'), ('Postgraduate', 'Postgraduate')], default='Undergraduate', max_length=100)),
                ('student_type', models.CharField(choices=[('International Student', 'International Student'), ('Local', 'Local')], default='Local', max_length=50)),
                ('min_gpa', models.DecimalField(decimal_places=2, default=3.0, max_digits=3)),
                ('criteria', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('ic_no', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('programme', models.CharField(max_length=200)),
                ('interview_date', models.DateField()),
                ('interview_time', models.CharField(max_length=20)),
                ('interview_timezone', models.CharField(max_length=50)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approved_applications',
            },
        ),
    ]
