# Generated by Django 4.2.27 on 2026-01-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='education_level',
            field=models.CharField(choices=[('Foundation', 'Foundation'), ('Undergraduate', 'Undergraduate'), ('Diploma', 'Diploma'), ('Postgraduate', 'Postgraduate')], default='Undergraduate', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='min_gpa',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='student_type',
            field=models.CharField(choices=[('International Student', 'International Student'), ('Local', 'Local')], default='Local', max_length=50),
        ),
    ]
