# Generated by Django 4.2.27 on 2026-01-31 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committee', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='criteria',
            new_name='notes',
        ),
        migrations.CreateModel(
            name='ScholarshipCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(help_text='e.g. SPM, STPM, UEC, Foundation', max_length=100)),
                ('requirement', models.CharField(help_text='e.g. 9As, CGPA 3.50', max_length=200)),
                ('entitlement', models.CharField(help_text='e.g. 100% Tuition Fee Waiver', max_length=200)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_list', to='committee.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
