# Generated by Django 6.0.1 on 2026-01-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
