# Generated by Django 4.2.27 on 2026-01-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
