# Generated by Django 6.0 on 2026-02-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='min_gpa',
        ),
        migrations.AddField(
            model_name='scholarshipcriteria',
            name='criteria_type',
            field=models.CharField(choices=[('GPA', 'Minimum GPA'), ('A_COUNT', 'Number of As'), ('TEXT', 'Text Only / Manual')], default=3.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarshipcriteria',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPA or number of As', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipcriteria',
            name='entitlement',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='scholarshipcriteria',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scholarshipcriteria',
            name='requirement',
            field=models.CharField(max_length=200),
        ),
    ]
