# Generated by Django 6.0 on 2026-01-30 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_interview_location_interview_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='reviewer',
            new_name='committee',
        ),
    ]
