# Generated by Django 6.0 on 2026-02-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_remove_scholarship_min_gpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipcriteria',
            name='requirement',
        ),
    ]
