# Generated by Django 4.2.27 on 2026-01-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_interview_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='entitlement',
            field=models.CharField(default='100% discount', help_text='e.g., 100% Tuition Fee Waiver, RM5000, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='grade_requirement',
            field=models.CharField(default='9As and above', help_text='e.g., 9As, CGPA 3.5, etc.', max_length=200),
        ),
    ]
