# Generated by Django 6.0 on 2026-01-31 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_rename_criteria_scholarship_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='min_gpa',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
