# Generated by Django 6.0 on 2026-01-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_alter_scholarship_min_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.CharField(default='MMU', max_length=255),
        ),
    ]
