# Generated by Django 6.0 on 2026-02-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_remove_scholarshipcriteria_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipcriteria',
            name='qualification',
            field=models.CharField(choices=[('SPM', 'SPM'), ('STPM', 'STPM'), ('UEC', 'UEC'), ('Foundation', 'Foundation/Matriculation'), ('Diploma', 'Diploma'), ('Undergraduate', 'Undergraduate Degree')], max_length=100),
        ),
    ]
