# Generated by Django 4.2.27 on 2026-01-31 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_scholarship_entitlement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='entitlement',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='grade_requirement',
        ),
        migrations.CreateModel(
            name='ScholarshipCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(help_text='e.g. SPM, STPM, UEC, Foundation', max_length=100)),
                ('requirement', models.CharField(help_text='e.g. 9As, CGPA 3.50', max_length=200)),
                ('entitlement', models.CharField(help_text='e.g. 100% Tuition Fee Waiver', max_length=200)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_list', to='committee.scholarship')),
            ],
        ),
    ]
