# Generated by Django 6.0 on 2026-02-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0005_alter_scholarshipcriteria_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipcriteria',
            name='qualification',
            field=models.CharField(choices=[('SPM', 'SPM'), ('STPM/A-Level', 'STPM/A-Level'), ('UEC', 'UEC'), ('Foundation', 'Foundation/Matriculation'), ('Diploma', 'Diploma'), ('Undergraduate', 'Undergraduate Degree')], max_length=100),
        ),
    ]
