# Generated by Django 4.2.27 on 2026-01-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0005_remove_scholarship_entitlement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='criteria',
            new_name='notes',
        ),
    ]
