# Generated by Django 6.0.1 on 2026-01-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0007_reviewchecklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewChecklist',
        ),
    ]
