# Generated by Django 6.0 on 2026-02-02 08:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0007_alter_scholarshipcriteria_min_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipcriteria',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPA or number of As (0.00 – 4.00)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
