# Generated by Django 4.2.27 on 2026-01-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0008_delete_reviewchecklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='application',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='application',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='scholarship',
        ),
        migrations.DeleteModel(
            name='ApprovedApplication',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
