# Generated by Django 6.0.1 on 2026-01-24 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0009_remove_guardian_application_and_more'),
        ('reviewer', '0005_eligibilitycheck_leadership_committee_and_more'),
        ('student', '0002_scholarshipapplication_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='student.scholarshipapplication'),
        ),
        migrations.AlterField(
            model_name='approvedapplication',
            name='original_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.scholarshipapplication'),
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        migrations.DeleteModel(
            name='ScholarshipApplication',
        ),
    ]
