# Generated by Django 4.2.27 on 2026-01-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_reviewerassignment_score_and_more'),
        ('committee', '0009_remove_guardian_application_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScholarshipApplication',
        ),
    ]
